### ISSUE TITLE
Custom resource functions

### ISSUE THREAD

**Issue by TMiguelT** [ESSS/flask-restalchemy#44]
Hi all, I think this project is an excellent idea, since manually stitching together Flask + SQLAlchemy + Flask-restful + Marshmallow involves a lot of repetition and boilerplate.

However, I realise that for my project, I need to be able to add custom view endpoints, so I can add filter logic to them, and other behaviour that handles the GET args. There seems to be some already existing code that does this kind of thing, but is it possible to fully customize it? I can envisage the default filter builder not working exactly for my use-case. In addition, would it be possible to document these more advanced features?

**Comment by igortg** [comment]
Hi,

Currently, is not very easy to replace the query that is made based on the GET arguments. You'd need to extend the `ModelResource` class to process your custom query and also extend `Api` class to use this new resource instead of the original `ModelResource`.

Another approach would be change the current `Api` class to allow the customization of the method [query_from_request](https://github.com/ESSS/flask-restalchemy/blob/a0a203684b4c6bee1fb610909799ea29ae1701d3/src/flask_restalchemy/resources/querybuilder.py#L6). A PR with this change would be welcome.

Current doc is very basic, we'll try to give it some love in the next weeks.

**Comment by igortg** [comment]
We added a `query_modifier` parameter to `add_model` method that receives a callable that gets a `Query` object and returns a modified `Query`. I guess this would solve @TMiguelT issue.
